import { Routes } from '@angular/router';
import { Login } from './login/login';

export const routes: Routes = [
    { path: '', component: Login, title: "Log In | SNL Nigeria Insiders", pathMatch: 'full'},
    { path: 'onboarding', loadComponent: () => import('./verify-code/verify-code').then(m => m.VerifyCode), title: "Onboarding | SNL Nigeria Insiders"},
    { path: 'home', loadComponent: () => import('./dashboard/dashboard').then(m => m.Dashboard), title: "Dashboard | SNL Nigeria Insiders"},
    { path: 'hiring', loadComponent: () => import('./hiring/hiring').then(m => m.Hiring), title: "Hiring | SNL Nigeria Insiders"},
    { path: 'hiring/positions', loadComponent: () => import('./positions/positions').then(m => m.Positions), title: "Positions - Hiring | SNL Nigeria Insiders"},
    { path: 'hiring/hiring-rounds', loadComponent: () => import('./hiring-rounds/hiring-rounds').then(m => m.HiringRounds), title: "Hiring Rounds - Hiring | SNL Nigeria Insiders"},
    { path: 'hiring/create-position', loadComponent: () => import('./create-position/create-position').then(m => m.CreatePosition), title: "Create Position - Hiring | SNL Nigeria Insiders"},
    { path: 'hiring/start-hiring-round', loadComponent: () => import('./start-hiring-round/start-hiring-round').then(m => m.StartHiringRound), title: "Start Hiring Round - Hiring | SNL Nigeria Insiders"},
    { path: 'hiring/hiring-rounds/:r_id', loadComponent: () => import('./hiring-round/hiring-round').then(m => m.HiringRound), title: "Hiring Round - Hiring | SNL Nigeria Insiders"},
    { path: 'hiring/hiring-rounds/:r_id/applications', loadComponent: () => import('./applications/applications').then(m => m.Applications), title: "Hiring Round Applications - Hiring | SNL Nigeria Insiders"},
    { path: 'staff', loadComponent: () => import('./staff/staff').then(m => m.Staff), title: "Staff | SNL Nigeria Insiders"},
    { path: 'staff/add-personnel', loadComponent: () => import('./add-admin/add-admin').then(m => m.AddAdmin), title: "Add Personnel | SNL Nigeria Insiders"},
    { path: 'support', loadComponent: () => import('./queries/queries').then(m => m.Queries), title: "Support Queries | SNL Nigeria Insiders"},
    { path: 'settings', loadComponent: () => import('./settings/settings').then(m => m.Settings), title: "Account Settings | SNL Nigeria Insiders"},
    { path: 'trainings', loadComponent: () => import('./trainings/trainings').then(m => m.Trainings), title: "Trainings | SNL Nigeria Insiders"},
    { path: 'trainings/create-training', loadComponent: () => import('./create-training/create-training').then(m => m.CreateTraining), title: "Create Trainings - Trainings | SNL Nigeria Insiders"},
    { path: 'trainings/manage-trainings', loadComponent: () => import('./manage-trainings/manage-trainings').then(m => m.ManageTrainings), title: "Manage Trainings - Trainings | SNL Nigeria Insiders"},
    { path: 'trainings/manage-training/:t_id', loadComponent: () => import('./manage-training/manage-training').then(m => m.ManageTraining)},
    { path: 'trainings/available-trainings', loadComponent: () => import('./available-trainings/available-trainings').then(m => m.AvailableTrainings), title: "Available Trainings - Trainings | SNL Nigeria Insiders"},
    { path: 'trainings/take-training/:t_id', loadComponent: () => import('./take-training/take-training').then(m => m.TakeTraining)},
    { path: 'departments', loadComponent: () => import('./departments/departments').then(m => m.Departments), title: "Departments | SNL Nigeria Insiders"},
    { path: 'departments/create-department', loadComponent: () => import('./create-department/create-department').then(m => m.CreateDepartment), title: "Create Department - Departments | SNL Nigeria Insiders"},
    { path: 'departments/manage-department/:d_id', loadComponent: () => import('./manage-department/manage-department').then(m => m.ManageDepartment), title: "Manage Department - Departments | SNL Nigeria Insiders"},
    { path: 'management', loadComponent: () => import('./management/management').then(m => m.Management), title: "Manage Direct Reports | SNL Nigeria Insiders"},
    { path: 'management/manage-direct-report/:r_id', loadComponent: () => import('./manage-direct-report/manage-direct-report').then(m => m.ManageDirectReport), title: "Manage Direct Report | SNL Nigeria Insiders"},
    { path: 'staff/manage-personnel/:a_id', loadComponent: () => import('./manage-personnel/manage-personnel').then(m => m.ManagePersonnel), title: "Manage Personnel | SNL Nigeria Insiders"},
    { path: 'access-levels', loadComponent: () => import('./access-levels/access-levels').then(m => m.AccessLevels), title: "Access Levels | SNL Nigeria Insiders"},
    { path: 'access-levels/create-access-level', loadComponent: () => import('./create-access-level/create-access-level').then(m => m.CreateAccessLevel), title: "Create Access Level - Access Levels | SNL Nigeria Insiders"},
    { path: 'access-levels/edit-access-level/:l_id', loadComponent: () => import('./edit-access-level/edit-access-level').then(m => m.EditAccessLevel), title: "Edit Access Level - Access Levels | SNL Nigeria Insiders"},
    { path: 'calendar', loadComponent: () => import('./calendar/calendar').then(m => m.Calendar), title: "Corporate Calendar | SNL Nigeria Insiders"},
    { path: 'calendar/edit', loadComponent: () => import('./calendar-edit/calendar-edit').then(m => m.CalendarEdit), title: "Update Corporate Calendar | SNL Nigeria Insiders"},
    // { path: 'onboarding', loadComponent: () => import('./login/login').then(m => m.Login), title: "Onboarding | SNL Nigeria Insiders"},
];
